
[window]
decorations = "Full"
opacity = 0.90
blur = true
startup_mode = "SimpleFullscreen"
# startup_mode = "Fullscreen"
dynamic_title = false
resize_increments = true

[scrolling]
history = 5000

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 20
builtin_box_drawing = false

[colors]
transparent_background_colors = true

[cursor]
style = { blinking = "Always" }
blink_timeout = 0

[keyboard]
bindings = [
  { key = "F", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
  { key = "V", mods = "Command|Shift", action = "ToggleViMode" },
]

[general]
import = ["~/.config/alacritty/themes/themes/smoooooth.toml"]
